feat:add consumer override of quotas
terraform-google-modules/terraform-google-project-factory pull request #468
Opened 2020-10-05 06:36 UTC by ericyz

There are quite a few use cases to add customer quota override during the project creation process. The changes is to add the capability into the CFT module

2020-10-19 17:40 UTC, morgante requested changes

2021-03-15 12:48 UTC, ocervell commented
I'd love to see this land. @ericyz would you please address @morgante 's comments so that we can add this to Project Factory ?

2021-03-16 02:28 UTC, ericyz commented
Oh, I missed out this one. For sure, I am updating it now

2021-03-16 03:11 UTC, morgante commented
@ericyz Please address linting errors.

2021-03-16 17:08 UTC, morgante requested changes

2021-03-16 17:08 UTC, morgante commented on examples/shared_vpc/main.tf
> +  consumer_quotas = var.consumer_quotas
We're trying to have examples use hard-coded values where possible, let's put a representative example in here.

2021-03-16 17:08 UTC, morgante commented on modules/gsuite_enabled/README.md
> +| consumer\_quotas | The quotas configuration you want to override to the project. | <pre>list(object({<br>    service = string,<br>    metric  = string,<br>    limit   = string,<br>    value   = str
```suggestion
| consumer\_quotas | The quotas configuration you want to override for the project. | <pre>list(object({<br>    service = string,<br>    metric  = string,<br>    limit   = string,<br>    value   = string,<br>  }))</pre> | `[]` | no |
```

2021-03-16 17:08 UTC, morgante commented on modules/quota_manager/main.tf
> +  consumer_quotas = { for index, quota in var.consumer_quotas : index => quota }
This should probably be indexed by service+metric. Ordered indexing is brittle.

2021-03-18 22:47 UTC, morgante approved these changes

2021-03-18 22:50 UTC, merged