Fix/readme
terraform-google-modules/terraform-google-project-factory pull request #724
Opened 2022-05-22 10:40 UTC by nikhilmakhijani

Updating variable description for random_project_id to explain the use case and why we need it. Issue no #723

2022-05-24 16:08 UTC, bharathkkb requested changes
Thanks for the PR @nikhilmakhijani
Lets move the rationale to our [FAQ](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/master/docs/FAQ.md)

2023-02-14 21:26 UTC, ericsampson commented
@bharathkkb can this be reopened? It would still be good information to add (with the update regarding project id behavior after deletion that you mentioned).

2023-06-15 15:24 UTC, g-awmalik requested changes

2023-06-15 15:24 UTC, g-awmalik commented on docs/FAQ.md
> +## What is the requirement of `random_project_id` variable?
```suggestion
## Requirement for `random_project_id`
```

2023-06-15 15:59 UTC, g-awmalik approved these changes

2023-06-15 16:00 UTC, merged