Code cleanup
terraform-google-modules/terraform-google-project-factory pull request #733
Opened 2022-07-28 17:22 UTC by drandell

Mostly style and consistency changes with some new configuration options and one additional output. 
I don't have an org setup so I can't test this myself but I've not fundamentally changed anything here. 

Changes:
* Add currency code as an option to the budget module
* Add storage class to the core module
* Closes https://github.com/terraform-google-modules/terraform-google-project-factory/issues/674 
* Add description under the value in all outputs to make the code reading more consistent 
* Make the version constraint consistent across each module

2022-07-28 17:49 UTC, drandell commented
> ```shell
> quota_manager
> ```

doesn't make sense, this resource was GA according to the release notes in 2020? 
https://github.com/hashicorp/terraform-provider-google/releases/tag/v3.15.0

2022-07-28 23:43 UTC, bharathkkb requested changes
Thanks for the PR @drandell 
You will have to split this PR into a few PRs separating out features, formatting fixes and any breaking changes like provider min version bumps. I noticed a few in this PR - we only tend to update these if there is a new feature we want to include in the module as these are breaking changes.

2022-07-28 23:43 UTC, bharathkkb commented on main.tf
> -
We should keep line btw blocks for readability.

2022-07-28 23:43 UTC, bharathkkb commented on modules/app_engine/outputs.tf
> +  description = "The location app engine is serving from"
We usually do description followed by value. Lets revert these.

2022-07-28 23:43 UTC, bharathkkb commented on modules/app_engine/versions.tf
> +      version = ">= 4.11.0, < 5.0.0"
Any reason why we are bumping versions?

2022-07-28 23:43 UTC, bharathkkb commented on modules/budget/versions.tf
> +      version = ">= 4.11.0, < 5.0.0"
We should not need to bump this. currency_code seems to not need 4.11?

2022-07-28 23:43 UTC, bharathkkb commented on modules/core_project_factory/main.tf
> -  provider = google-beta
We should not change providers here and throughout

2022-07-29 00:06 UTC, apeabody commented on modules/core_project_factory/versions.tf
> +      version = ">= 4.11.0, < 5.0.0"
@drandell - Is there a reason to bump the minimum version for core_project sub-module?  If not, let's please leave as-is as the sub-module could be used independently of the main module or sub-modules that require 4.5.

FYI: `~> 4.11` is functionally the same as `>= 4.11.0, < 5.0.0`

2022-08-19 10:24 UTC, closed without merging